<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="background-color: rgba(255, 255, 255, 0.8);">
        <div class="card-header text-center" style="background-color: rgba(0, 100, 50, 0.9); color: white;">
            <h4 class="mb-0" style="font-size: 1.2rem; text-transform: uppercase;">Agregar Club</h4>
        </div>
        <div class="card-body">
            <form action="newEquipo" method="POST" class="row g-3 d-flex justify-content-center">
                <div class="col-md-2">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="nombre" required>
                </div>
                <div class="col-md-2">
                    <label for="ciudad" class="form-label">Ciudad</label>
                    <input type="text" class="form-control" name="ciudad" required>
                </div>
                <div class="col-md-2">
                    <label for="pais" class="form-label">Pais</label>
                    <input type="text" class="form-control" name="pais" required>
                </div>
                <div class="col-md-2">
                    <label for="liga" class="form-label">Liga</label>
                    <input type="text" class="form-control" name="liga" required>
                </div>
                <div class="col-md-2">
                    <label for="anio" class="form-label">Año De Fundacion</label>
                    <input type="text" class="form-control" name="anio" required>
                </div>
                <div class="col-md-12 d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-success">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
