<?php require 'templates/layout/header.phtml' ?>
<a id="btn-volver" href="equipos/" type="button" class='btn btn-details btn-sm ml-auto'></a>

    

<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="background-color: rgba(255, 255, 255, 0.8); max-width: 600px;">
        <div class="card-header text-center" style="background-color: rgba(0, 0, 0, 0.9); color: white;">
            <h4 class="mb-0" style="font-size: 1.2rem; text-transform: uppercase;">Editar Club</h4>
        </div>
        <div class="card-body">
            <form action="editEquipo/<?= $equipo->id_equipo ?>" method="POST" class="row g-3 d-flex justify-content-center">
                
                <!-- Primera fila -->
                <div class="col-md-6">
                    <label for="nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" name="nombre" value='<?= $equipo->nombre ?>' required>
                </div>

                <!-- Segunda fila -->
                <div class="col-md-6">
                    <label for="ciudad" class="form-label">ciudad</label>
                    <input type="text" class="form-control" name="ciudad" value='<?= $equipo->ciudad ?>' required>
                </div>
                <div class="col-md-6">
                    <label for="pais" class="form-label">pais</label>
                    <input type="text" class="form-control" name="pais" value='<?= $equipo->pais ?>' required>
                </div>
                <div class="col-md-6">
                    <label for="liga" class="form-label">liga</label>
                    <input type="text" class="form-control" name="liga" value='<?= $equipo->liga ?>' required>
                </div>
                <div class="col-md-6">
                    <label for="anio" class="form-label">año</label>
                    <input type="number" class="form-control" name="anio" value='<?= $equipo->anio ?>' required>
                </div>

                <!-- Botón de enviar -->
                <div class="col-md-12 d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-success">Modificar</button>
                </div>
            </form>
        </div>
    </div>
</div>


<?php require 'templates/layout/footer.phtml' ?>
