<?php require 'templates/layout/header.phtml' ?>
<div class="text-center background-color: rgba(0, 100, 50);">
<h1 class="text-center fw-bold" style="font-family: 'Arial', sans-serif; font-size: 2.5rem; color: #169f09ff; text-shadow: none;">Catálogo de Futbol</h1>
<p class="text-center" style="font-family: 'Arial', sans-serif; font-size: 1.2rem; color: #3b3a3aff; margin-top: 10px;">Informacion de clubes y jugadores</p>

 </div>
        <div class="secciones mt-5">
    <div class="row">
        <div class="col-md-6">
            <section class="jugadores bg-black p-4 shadow-sm d-flex flex-column justify-content-center align-items-center background-color: rgba(0, 1000, 50);" style="height: 320px; border-radius: 1000px;  background-image: url('img/fondo-jugadores.jpg');
         background-size: cover; 
         background-position: center; 
         background-repeat: no-repeat;">
                <h2 class="fw-bold text-center text-uppercase text-white" style="font-family: 'Arial', sans-serif; font-size: 1.75rem;">Jugadores</h2>
                
                <a class="btn btn-success btn-lg mt-2" href="jugadores">Ver</a>
            </section>
        </div>
        <div class="col-md-6">
            <section class="equipos bg-black p-4 shadow-sm d-flex flex-column justify-content-center align-items-center background-color: rgba(0, 100, 50);" style="height: 320px; border-radius: 1000px;  background-image: url('img/fondo-equipos.jpg');
         background-size: cover; 
         background-position: center; 
         background-repeat: no-repeat;">
                <h2 class="fw-bold text-center text-uppercase text-white" style="font-family: 'Arial', sans-serif; font-size: 1.75rem; ">equipos</h2>
                
                <a class="btn btn-success btn-lg mt-2" href="equipos">Ver</a>
            </section>
        </div>
    </div>
</div>




       

   


 




        

<?php require 'templates/layout/footer.phtml' ?>