<?php require 'templates/layout/header.phtml' ?>


<a id="btn-volver" href="home/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<h2 class="mb-5 mt-5 fw-bold text-center text-uppercase" style="font-family: 'Poppins', sans-serif; font-size: 2.5rem; background: -webkit-linear-gradient(45deg, #6c757d, #495057); -webkit-background-clip: text; -webkit-text-fill-color: transparent; letter-spacing: 3px;">
  Equipos
</h2>

<ul class="list-group">
    <?php foreach($equipos as $equipo): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center pb-3 shadow-sm rounded mb-3">
            <div>
                <p class="mb-0 h5"><b><?= $equipo->nombre ?></b></p> 
            </div>
            <div class="actions d-flex align-items-center">
                <a id="btn-ver" href="viewEquipo/<?= $equipo->id_equipo ?>" type="button" class="btn btn-info btn-sm mx-2 fw-bold">
                    <i>Info</i>
                </a> 
                <?php if(isset($_SESSION['USER_ID'])) : ?>
                    <a id="btn-editar" href="showEditEquipo/<?= $equipo->id_equipo ?>" type="button" class="btn btn-warning btn-sm mx-2 border-0">
                    <i class="bi bi-pencil"></i> 
                    </a>
                    <a id="btn-eliminar" href="deleteEquipo/<?= $equipo->id_equipo ?>" type="button" class="btn btn-danger btn-sm d-flex align-items-center mx-2">
                    <i class="fas fa-trash-alt" style="color: white;"></i> 
                    </a>
                    <?php endif ?>
               
            </div>
        </li>
    <?php endforeach; ?>
</ul>











<?php if (isset($_SESSION['USER_ID'])) : 
    require 'templates/agregarEquipo.phtml';
endif; ?>


<?php require 'templates/layout/footer.phtml' ?>
