<?php require 'templates/layout/header.phtml' ?>


<a id="btn-volver" href="home/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<h2 class="mb-5 mt-5 fw-bold text-center text-uppercase" style="font-family: 'Poppins', sans-serif; font-size: 2.5rem; background: -webkit-linear-gradient(45deg, #6b7b62ff, #095217ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; letter-spacing: 3px;">
  Jugadores
</h2>

<ul class="list-group">
    <?php foreach($jugadores as $jugador): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center pb-3 shadow-sm rounded mb-3">
            <div>
                <p class="mb-0 h5"><b><?= $jugador->nombre ?></b></p>
                <p class="text-muted mb-0" style="font-size: 0.9rem;"><?= $jugador->nombre_club ?></p> <!-- Texto más pequeño y en gris -->
            </div>
            <div class="actions d-flex align-items-center">
                <a id="btn-ver" href="viewJugador/<?= $jugador->id_jugador ?>" type="button" class="btn btn-info btn-sm mx-2 fw-bold">
                    <i>Info</i>
                </a>
                <?php if(isset($_SESSION['USER_ID'])) : ?> 
                <a id="btn-editar" href="showEditJugador/<?= $jugador->id_jugador ?>" type="button" class="btn btn-warning btn-sm mx-2 border-0">
                    <i class="bi bi-pencil"></i>
                </a>
                <a id="btn-eliminar" href="deleteJugador/<?= $jugador->id_jugador ?>" type="button" class="btn btn-danger btn-sm d-flex align-items-center mx-2">
                    <i class="fas fa-trash-alt" style="color: white;"></i>
                </a>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>












<?php if (isset($_SESSION['USER_ID'])) : 
    require 'templates/agregarJugador.phtml';
endif; ?>



<?php require 'templates/layout/footer.phtml' ?>
