<?php require 'templates/layout/header.phtml' ?>

<a id="btn-volver" href="jugadores/" type="button" class='btn btn-details btn-sm ml-auto'></a>

<div class="container mt-5">
    <div class="card text-left shadow-sm mx-auto" style="width: 25rem; height: auto;">
        <div class="card-header text-center" style="background-color: rgba(173, 166, 166, 0.8); color: white;">
            <h2 class="mb-0"><b><?= $jugador->nombre ?></b></h2>
        </div>
        <div class="card-body d-flex flex-column" style="height: 150%;">
            <ul class="list-group list-group-flush flex-fill">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Nacido en:</strong> <span><?= $jugador->pais ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Posición:</strong> <span><?= $jugador->posicion ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Fecha de nacimiento:</strong> <span><?= $jugador->fecha_nacimiento ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <strong>Club:</strong> <span><?= $jugador->nombre_club ?></span>
                </li>
            </ul>
        </div>
    </div>
</div>









<?php require 'templates/layout/footer.phtml' ?>